### ISSUE TITLE
I kinda wanna try out gruvbox and gruvbox light, but I'm too lazy to add them

### ISSUE THREAD

**Issue by buffet** [buffet/rice#2]

**Comment by JavaCafe01** [comment]
ask elkowar to do it

**Comment by buffet** [comment]
Good idea.

@ElKowar, I was told you ask you? 🥺

**Comment by elkowar** [comment]
@buffet I can PR my gruvbox config this evening if you want... It's already in my dotfiles tho ^^ I already have my 4 hacktober PRs
