### ISSUE TITLE
Add XMonad support

### ISSUE THREAD

**Issue by elkowar** [buffet/rice#3]
This rice desperately needs support for an X-based window manager, such as to make use of the brilliance of the stenotype system using plover. Thus, XMonad support should be added.

## Acceptance criteria
- XMonad is configured and installed
- @buffet knows how to use and configure the relevant parts of XMonad
- A sufficient amount of Haskell jokes has been made

**Comment by 6gk** [comment]
Do this so I can make an issue about removing xmonad support
uwu

**Comment by 6gk** [comment]
Bufufer plz add me as collaborator so I can rm -rf this issue

**Comment by elkowar** [comment]
@6gk see https://github.com/elkowar/eww/issues/10

**Comment by elkowar** [comment]
@buffet can we close this, given that XMonad support is now implemented?

**Comment by buffet** [comment]
I'm not sure if we've made enough Haskell jokes, but we can always reopen this later.
